name: amdp_offline_linear
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyter
  - gymnasium
  - cvxpy 
  - matplotlib >= 3.8
  - openpyxl >= 3.0
  - pandas >= 2.0
  - pip >= 24.0
  - pyarrow
  - python = 3.12
  - scikit-learn >= 1.4
  - sqlalchemy
  - pytorch >= 2.0
  - pip:
      - pyjokes == 0.6.0
      - plotly == 5.24.0
      - seaborn == 0.13.2
